// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHtU2rdnMh-0QQaS3orqMoC5syluPGxE',
    appId: '1:768838600640:web:32618fab8d547ea0306a25',
    messagingSenderId: '768838600640',
    projectId: 'task-management-firestore',
    authDomain: 'task-management-firestore.firebaseapp.com',
    storageBucket: 'task-management-firestore.appspot.com',
    measurementId: 'G-58S61PBE09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhMAVxj02ZYcpKp9R-O2IrborWMOyckuE',
    appId: '1:768838600640:android:87b02e2a327c9374306a25',
    messagingSenderId: '768838600640',
    projectId: 'task-management-firestore',
    storageBucket: 'task-management-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxhv8PqQLFkdjOpoLEO3RTJfF4Om90FQc',
    appId: '1:768838600640:ios:bcc105b4873bbf21306a25',
    messagingSenderId: '768838600640',
    projectId: 'task-management-firestore',
    storageBucket: 'task-management-firestore.appspot.com',
    iosClientId: '768838600640-jnfokfv4hl9f87d62pg4re0e9sdmvpto.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanagemet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxhv8PqQLFkdjOpoLEO3RTJfF4Om90FQc',
    appId: '1:768838600640:ios:69ceabe5814f3300306a25',
    messagingSenderId: '768838600640',
    projectId: 'task-management-firestore',
    storageBucket: 'task-management-firestore.appspot.com',
    iosClientId: '768838600640-88i0tffoq3jpqk4j5gu694uhitnti05j.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanagemet.RunnerTests',
  );
}
